
FROM eclipse-temurin:24-jdk

RUN apt-get update && apt-get install -y \
    curl \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY gradle/ gradle/
COPY gradlew .
COPY gradlew.bat .
COPY build.gradle .
COPY settings.gradle .

COPY src/ src/

RUN chmod +x gradlew

RUN ./gradlew build -x test --no-daemon
CMD ["./gradlew", "test", "--no-daemon"]
