server:
  port: 8088


spring:
  flyway:
    enabled: true
  datasource:
    url: jdbc:postgresql://PostgreSQL:5432/db_MovieApp
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http.converter.json.MappingJackson2HttpMessageConverter: DEBUG

